Feature/rest api
flowsforapex/apex-flowsforapex pull request #642
Opened 2023-06-18 12:29 UTC by jdoppelreiter

2023-06-21 08:37 UTC, commi235 reviewed
I'd suggest to move the types into a package as it seems we don't need Schema level types.

2023-06-21 08:37 UTC, commi235 commented on src/migrations/22.2_to_23.1/feature-rest-api.sql
> +create type flow_rest_role_ot as object
Do we need Schema level types?

2023-06-21 08:37 UTC, commi235 commented on src/views/flow_rest_process_vars_vw.sql
> +              , 'clob',     pv.prov_var_num
Doesn't look right

2023-06-21 08:37 UTC, commi235 commented on src/types/flow_rest_role_ot.sql
Check if we need Schema level types

2023-06-21 08:37 UTC, commi235 commented on src/types/flow_rest_roles_nt.sql
Schema level types continued

2023-06-21 08:37 UTC, commi235 commented on src/plsql/flow_rest_auth.pkb
> +      PIPE ROW (flow_rest_role_ot ( rec_roles.id, rec_roles.name ));
Pipelined table function does not need Schema level types.
Types can be declared in the package header..

2023-06-21 22:34 UTC, commi235 approved these changes

2023-06-21 22:36 UTC, commi235 requested changes
flow_rest_process_vars_vw doesn't look right.

2023-06-21 22:36 UTC, commi235 commented on src/views/flow_rest_process_vars_vw.sql
> +              , 'clob',     pv.prov_var_num
date and clob shouldn't use pro_var_num here.

2023-06-22 07:16 UTC, jdoppelreiter commented
Thanks for finding it... view flow_rest_process_vars_vw adapted

2023-06-22 14:26 UTC, commi235 approved these changes

2023-06-22 14:26 UTC, merged