Issues/issue 675 support db 23c
flowsforapex/apex-flowsforapex pull request #685
Opened 2023-10-02 18:40 UTC by rallen2010

Fixes Issues #676 and #675  which prevent operation with Oracle database 23c (23.3.0)
- fixes a compile error in flow_log_admin that was allowed in 19c!
- workaround a SQL execution error in 23.3.0 affecting flow_engine and flow_engine_util when getting lane information from diagrams without lanes, which caused Flows for APEX to fail.

The fix for #676 re-touches the file changed in #681 - so I have created a combo patch file that includes fixes 675, 676 and 681.  All three are required to support 23.1.
Runs regression cleanly on 19c and 23c (23.3.0).

I've also made some changes to some regression tests, test apps, and test diagrams / models so that it should be much easier to install them on new test environments, including automated testing - by cleaning up and parameterising app_ids and usernames embedded into test scripts, apps and models.

2023-10-02 20:24 UTC, commi235 requested changes
added missing slash and new line to a file.
However that file should also be named differently and references updated.

2023-10-02 20:24 UTC, commi235 commented on test/plsql/test_constants.pkb
This should be .pks file as it's a package specification.

2023-10-02 20:24 UTC, commi235 commented on test/testing_readme.md
> +8. Edit the Test Constants file (test_constants.pkb) to set any appropriate User IDs and APEX APP IDs for the testing environment.
update file name once file is renamed

2023-10-02 20:58 UTC, rallen2010 commented on test/plsql/test_constants.pkb
Oops.   Good catch.   Thanks.

2023-10-02 20:58 UTC, rallen2010 commented on test/plsql/test_constants.pkb
fixed in commit below

2023-10-02 21:23 UTC, rallen2010 commented
Sorry, late change - just added test_constants.pks to the test install script as well...

2023-10-03 04:19 UTC, ralfmueller approved these changes

2023-10-03 09:11 UTC, commi235 approved these changes

2023-10-03 09:12 UTC, merged